import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { ClipboardCheckIcon, SearchIcon } from "@heroicons/react/outline";
import { useQuery } from "@apollo/client";
import { getAppointments } from "../src/lib/queries";
import { format } from "date-fns";
import DateInput from "../components/DateInput";
import TimePicker from "../components/TimePicker";
import Modal from "../components/Modal";
import it from "date-fns/esm/locale/it/index.js";
enum status {
  "Programada" = "PROGRAMADA",
  "atendida" = "ATENDIDA",
}
type appointment = {
  id?: number;
  placa: string;
  date: string;
  status: status;
};
const Home: NextPage = () => {
  const [info, setInfo] = useState<appointment>({
    placa: "",
    date: "",
    status: status.Programada,
  });
  const [showModal, setShowModal] = useState(false);

  const [date, setDate] = useState<Date>(new Date());
  const [time, setTime] = useState("");
  const { loading, error, data } = useQuery(getAppointments, {
    variables: { placa: info.placa },
  });

  const getInput = () => {
    const splittedDate = date?.toString().split(" ");
    const mappedDate = splittedDate?.map((val) =>
      val === "00:00:00" ? time : val
    );
    const joinedDate = mappedDate?.join(" ");

    return {
      date: joinedDate,
      placa: info.placa,
      status: status.Programada,
    };
  };
  const openModal = () => {
    if (time === "") return;
    if (date === new Date()) return;
    setShowModal(true);
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal
        show={showModal}
        _show={setShowModal}
        createAppointmentInput={getInput()}
      />
      <main className="bg-gray-200 min-h-screen">
        <div className="layout pt-4">
          <h1 className="font-bold text-xl text-center text-emerald-600">
            Bienvenido al sistema de citas
          </h1>

          {/* input cont */}
          <div className="mt-5 bg-white p-2 rounded-lg">
            <p className="text-center text-lg">
              Introduzca el numero de placa para agendar una cita
            </p>

            <div className="border-2 border-emerald-600 rounded-md flex px-3 py-2 mt-4">
              <SearchIcon className="w-5" />
              <input
                type="text"
                className="w-full outline-none bg-transparent ml-1"
                placeholder="AU5050"
                value={info.placa}
                onChange={(e) => setInfo({ ...info, placa: e.target.value })}
              />
            </div>

            {/* citas container */}

            <div className="">
              {loading === true ? (
                <p>Loading</p>
              ) : data.appointments.length === 0 ? (
                <p className="ml-3 mt-2 font-bold">
                  No Hay citas con este numero de placa
                </p>
              ) : (
                <>
                  {data.appointments.map((appt: appointment) => {
                    const date = new Date(appt.date);
                    const formatedDate = format(date, "d-LL-yyyy h-mbbb");

                    return (
                      <div
                        key={appt.id}
                        className="flex my-3 items-center w-full bg-green-200 rounded-md p-2"
                      >
                        <ClipboardCheckIcon className="w-6 mr-2" />

                        <p>{formatedDate}</p>
                        <p className="font-bold ml-2">{appt.status}</p>
                      </div>
                    );
                  })}
                </>
              )}
              {/* {data.appointments.length === 0 && (
                <p className="ml-3 mt-2 font-bold">
                  No Hay citas con este numero de placa
                </p>
              )} */}
            </div>
          </div>

          <div className="mt-5 bg-white p-2 rounded-lg">
            <p className="text-center text-lg">
              Seleccione la hora y fecha para agendar una nueva cita
            </p>

            <div className="flex justify-center mb-2">
              <TimePicker time={time} setTime={setTime} />
            </div>
            <DateInput date={date} setDate={setDate} />

            <button
              className="mt-6 flex items-center justify-center w-full rounded-xl bg-emerald-600 py-2 px-3 text-white text-xl cursor-pointer"
              onClick={openModal}
            >
              Agendar Nueva
            </button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
