import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { SearchIcon } from "@heroicons/react/outline";
enum status {
  "Programada" = "PROGRAMADA",
  "atendida" = "ATENDIDA",
}
type appointment = {
  placa: string;
  date: string;
  status: status;
};
const Home: NextPage = () => {
  const [info, setInfo] = useState<appointment>({
    placa: "",
    date: "",
    status: status.Programada,
  });

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-200 min-h-screen">
        <div className="layout pt-4">
          <h1 className="font-bold text-xl text-center text-emerald-600">
            Bienvenido al sistema de citas
          </h1>

          {/* input cont */}
          <div className="mt-5 bg-white p-2 rounded-lg">
            <p className="text-center text-lg">
              Introduzca el numero de placa para agendar una cita
            </p>

            <div className="border-2 border-emerald-600 rounded-md flex px-3 py-2 mt-4">
              <SearchIcon className="w-5" />
              <input
                type="text"
                className="w-full outline-none bg-transparent ml-1"
                placeholder="AU5050"
                value={info.placa}
                onChange={(e) => setInfo({ ...info, placa: e.target.value })}
              />
            </div>

            <button className="mt-6 flex items-center justify-center w-full rounded-xl bg-emerald-600 py-2 px-3 text-white text-xl cursor-pointer">
              Buscar
            </button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
